# Generated by Django 6.0.3 on 2026-03-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20260310_2014'),
        ('news', '0002_category_subscribers'),
    ]

    operations = [
    ]
