# Generated by Django 6.0.3 on 2026-03-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_merge_20260310_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
